name: Documentation CI
on: 
  push: 
    branches: 
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Installing packages
        run: npm install

      - name: Build Gridsome site
        run: yarn build
